services:

  auth-db:
    image: postgres:17
    container_name: ${DOCKER_POSTGRES_AUTH_DB_CONTAINER_NAME}
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${DOCKER_POSTGRES_AUTH_DB_NAME}
      POSTGRES_USER: ${DOCKER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}

    volumes:
      - auth_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-authdb}"]
      interval: 10s
      timeout: 5s
      retries: 1

    networks:
      - ezhomenet

  user-db:
    image: postgres:17
    container_name: ${DOCKER_POSTGRES_USER_DB_CONTAINER_NAME}
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${DOCKER_POSTGRES_USER_DB_NAME}
      POSTGRES_USER: ${DOCKER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}

    volumes:
      - user_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-userdb}"]
      interval: 10s
      timeout: 5s
      retries: 1

    networks:
      - ezhomenet

  user-app:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: ${DOCKER_USER_SERVICE_CONTAINER_NAME}
    restart: on-failure:1  

    depends_on:
      user-db:
        condition: service_healthy

    environment:
      USER_SERVICE_PORT: ${DOCKER_USER_SERVICE_PORT}
      USER_DB_URL: ${DOCKER_POSTGRES_USER_DB_URL}
      USER_DB_USERNAME: ${DOCKER_POSTGRES_USER}
      USER_DB_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}

    networks:
      - ezhomenet

  auth-app:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: ${DOCKER_AUTH_SERVICE_CONTAINER_NAME}
    restart: on-failure:1

    depends_on:
      auth-db:
        condition: service_healthy

    environment:
      AUTH_SERVICE_PORT: ${DOCKER_AUTH_SERVICE_PORT}
      USER_DB_URL: ${DOCKER_POSTGRES_AUTH_DB_URL}
      USER_DB_USERNAME: ${DOCKER_POSTGRES_USER}
      USER_DB_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}

    networks:
      - ezhomenet


  app:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    restart: on-failure:1
    environment:
      API_GATEWAY_SERVICE_PORT: ${DOCKER_API_GATEWAY_PORT}
      API_GATEWAY_AUTH_URL: ${DOCKER_API_GATEWAY_AUTH_URL}
      AUTH_SERVICE_CONTAINER_NAME: ${DOCKER_AUTH_SERVICE_CONTAINER_NAME}
      AUTH_SERVICE_PORT: ${DOCKER_AUTH_SERVICE_PORT}
      USER_SERVICE_CONTAINER_NAME: ${DOCKER_USER_SERVICE_CONTAINER_NAME}
      USER_SERVICE_PORT: ${DOCKER_USER_SERVICE_PORT}
    ports:
      - "4000:4000"
    networks:
      - ezhomenet

networks:
  ezhomenet:

volumes:
  user_data:
  auth_data:

