services:

  auth-db:
    image: postgres:17
    container_name: ${DOCKER_POSTGRES_AUTH_DB_CONTAINER_NAME}
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${DOCKER_POSTGRES_AUTH_DB_NAME}
      POSTGRES_USER: ${DOCKER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}

    volumes:
      - auth_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-authdb}"]
      interval: 10s
      timeout: 5s
      retries: 1

    networks:
      - ezhomenet

  user-db:
    image: postgres:17
    container_name: ${DOCKER_POSTGRES_USER_DB_CONTAINER_NAME}
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${DOCKER_POSTGRES_USER_DB_NAME}
      POSTGRES_USER: ${DOCKER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}

    volumes:
      - user_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-userdb}"]
      interval: 10s
      timeout: 5s
      retries: 1

    networks:
      - ezhomenet

  device-registry-db:
    image: postgres:17
    container_name: ${DOCKER_POSTGRES_DEVICE_REGISTRY_DB_CONTAINER_NAME}
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${DOCKER_POSTGRES_DEVICE_REGISTRY_DB_NAME}
      POSTGRES_USER: ${DOCKER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}

    volumes:
      - device_registry_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-deviceregistrydb}"]
      interval: 10s
      timeout: 5s
      retries: 1

    networks:
      - ezhomenet

  device-db:
    image: postgres:17
    container_name: ${DOCKER_POSTGRES_DEVICE_DB_CONTAINER_NAME}
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${DOCKER_POSTGRES_DEVICE_DB_NAME}
      POSTGRES_USER: ${DOCKER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}

    volumes:
      - device_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-devicedb}"]
      interval: 10s
      timeout: 5s
      retries: 1

    networks:
      - ezhomenet

  usage-db:
    image: postgres:17
    container_name: ${DOCKER_POSTGRES_USAGE_DB_CONTAINER_NAME}
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${DOCKER_POSTGRES_USAGE_DB_NAME}
      POSTGRES_USER: ${DOCKER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}

    volumes:
      - usage_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-usagedb}"]
      interval: 10s
      timeout: 5s
      retries: 1

    networks:
      - ezhomenet

  alert-db:
    image: postgres:17
    container_name: ${DOCKER_POSTGRES_ALERT_DB_CONTAINER_NAME}
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${DOCKER_POSTGRES_ALERT_DB_NAME}
      POSTGRES_USER: ${DOCKER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}

    volumes:
      - alert_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-alertdb}"]
      interval: 10s
      timeout: 5s
      retries: 1

    networks:
      - ezhomenet

  ingestion-redis:
      image: redis:7-alpine
      container_name: ${DOCKER_INGESTION_REDIS_CONTAINER_NAME}
      restart: unless-stopped

      volumes:
        - ingestion_redis_data:/data

      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 10s
        timeout: 5s
        retries: 1

      networks:
        - ezhomenet

  alert-redis:
      image: redis:7-alpine
      container_name: ${DOCKER_ALERT_REDIS_CONTAINER_NAME}
      restart: unless-stopped

      volumes:
        - alert_redis_data:/data

      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 10s
        timeout: 5s
        retries: 1

      networks:
        - ezhomenet

  kafka:
    image: apache/kafka:latest
    container_name: ${DOCKER_KAFKA_CONTAINER_NAME}
    restart: unless-stopped

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: INTERNAL
      KAFKA_LISTENERS: PLAINTEXT://:9092,INTERNAL://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${DOCKER_KAFKA_CONTAINER_NAME}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list > /dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

    networks:
      - ezhomenet

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: ${DOCKER_KAFKA_UI_CONTAINER_NAME}

    ports:
      - "8085:8080"

    environment:
      KAFKA_CLUSTERS_0_NAME: ${DOCKER_KAFKA_UI_CLUSTER_NAME}
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ${DOCKER_KAFKA_SERVER}

    networks:
      - ezhomenet

  user-app:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: ${DOCKER_USER_SERVICE_CONTAINER_NAME}
    restart: on-failure:1  

    depends_on:
      user-db:
        condition: service_healthy

    environment:
      USER_SERVICE_PORT: ${DOCKER_USER_SERVICE_PORT}
      GRPC_SERVER_PORT: ${DOCKER_USER_SERVICE_GRPC_PORT}
      USER_DB_URL: ${DOCKER_POSTGRES_USER_DB_URL}
      USER_DB_USERNAME: ${DOCKER_POSTGRES_USER}
      USER_DB_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}

    networks:
      - ezhomenet

  auth-app:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: ${DOCKER_AUTH_SERVICE_CONTAINER_NAME}
    restart: on-failure:1

    depends_on:
      auth-db:
        condition: service_healthy

    environment:
      AUTH_SERVICE_PORT: ${DOCKER_AUTH_SERVICE_PORT}
      GRPC_SERVER_PORT: ${DOCKER_AUTH_SERVICE_GRPC_PORT}
      USER_DB_URL: ${DOCKER_POSTGRES_AUTH_DB_URL}
      USER_DB_USERNAME: ${DOCKER_POSTGRES_USER}
      USER_DB_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      USER_SERVICE_ADDRESS: ${DOCKER_USER_SERVICE_CONTAINER_NAME}
      USER_SERVICE_GRPC_PORT: ${DOCKER_USER_SERVICE_GRPC_PORT}

    networks:
      - ezhomenet

  device-registry-app:
    build:
      context: ./device-registry-service
      dockerfile: Dockerfile
    container_name: ${DOCKER_DEVICE_REGISTRY_SERVICE_CONTAINER_NAME}
    restart: on-failure:1  

    depends_on:
      device-registry-db:
        condition: service_healthy

    environment:
      DEVICE_REGISTRY_SERVICE_PORT: ${DOCKER_DEVICE_REGISTRY_SERVICE_PORT}
      DEVICE_REGISTRY_GRPC_SERVER_PORT: ${DOCKER_DEVICE_REGISTRY_SERVICE_GRPC_PORT}
      DEVICE_REGISTRY_DB_URL: ${DOCKER_POSTGRES_DEVICE_REGISTRY_DB_URL}
      DEVICE_REGISTRY_DB_USERNAME: ${DOCKER_POSTGRES_USER}
      DEVICE_REGISTRY_DB_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}

    networks:
      - ezhomenet

  device-app:
    build:
      context: ./device-service
      dockerfile: Dockerfile
    container_name: ${DOCKER_DEVICE_SERVICE_CONTAINER_NAME}
    restart: on-failure:1  

    depends_on:
      device-db:
        condition: service_healthy

    environment:
      DEVICE_SERVICE_PORT: ${DOCKER_DEVICE_SERVICE_PORT}
      DEVICE_SERVICE_GRPC_SERVER_PORT: ${DOCKER_DEVICE_SERVICE_GRPC_PORT}

      DEVICE_SERVICE_DB_URL: ${DOCKER_POSTGRES_DEVICE_DB_URL}
      DEVICE_SERVICE_DB_USERNAME: ${DOCKER_POSTGRES_USER}
      DEVICE_SERVICE_DB_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}

      DEVICE_REGISTRY_SERVICE_ADDRESS: ${DOCKER_DEVICE_REGISTRY_SERVICE_CONTAINER_NAME}
      DEVICE_REGISTRY_SERVICE_GRPC_SERVER_PORT: ${DOCKER_DEVICE_REGISTRY_SERVICE_GRPC_PORT}

      INGESTION_SERVICE_ADDRESS: ${DOCKER_INGESTION_SERVICE_CONTAINER_NAME}
      INGESTION_SERVICE_GRPC_SERVER_PORT: ${DOCKER_INGESTION_SERVICE_GRPC_PORT}

      ALERT_SERVICE_ADDRESS: ${DOCKER_ALERT_SERVICE_CONTAINER_NAME}
      ALERT_SERVICE_GRPC_SERVER_PORT: ${DOCKER_ALERT_SERVICE_GRPC_PORT}

    networks:
      - ezhomenet

  ingestion-app:
    build:
      context: ./ingestion-service
      dockerfile: Dockerfile
    container_name: ${DOCKER_INGESTION_SERVICE_CONTAINER_NAME}
    restart: on-failure:1  

    depends_on:
      device-app:
        condition: service_started
      ingestion-redis:
        condition: service_healthy
      kafka:
        condition: service_healthy  

    environment:
      INGESTION_SERVICE_PORT: ${DOCKER_INGESTION_SERVICE_PORT}
      INGESTION_SERVICE_GRPC_SERVER_PORT: ${DOCKER_INGESTION_SERVICE_GRPC_PORT}

      INGESTION_SERVICE_REDIS_HOST: ${DOCKER_INGESTION_REDIS_CONTAINER_NAME}
      INGESTION_SERVICE_REDIS_PORT: ${DOCKER_INGESTION_SERVICE_REDIS_PORT}

      KAFKA_BOOTSTRAP_SERVERS: ${DOCKER_KAFKA_SERVER}

      DEVICE_SERVICE_ADDRESS: ${DOCKER_DEVICE_SERVICE_CONTAINER_NAME}
      DEVICE_SERVICE_GRPC_SERVER_PORT: ${DOCKER_DEVICE_SERVICE_GRPC_PORT}

    networks:
      - ezhomenet

  usage-app:
    build:
      context: ./usage-service
      dockerfile: Dockerfile
    container_name: ${DOCKER_USAGE_SERVICE_CONTAINER_NAME}
    restart: on-failure:1  

    depends_on:
      usage-db:
        condition: service_healthy
      kafka:
        condition: service_healthy

    environment:
      USAGE_SERVICE_PORT: ${DOCKER_USAGE_SERVICE_PORT}
      KAFKA_BOOTSTRAP_SERVERS: ${DOCKER_KAFKA_SERVER}

      USAGE_SERVICE_DB_URL: ${DOCKER_POSTGRES_USAGE_DB_URL}
      USAGE_SERVICE_DB_USERNAME: ${DOCKER_POSTGRES_USER}
      USAGE_SERVICE_DB_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}

    networks:
      - ezhomenet

  alert-app:
    build:
      context: ./alert-service
      dockerfile: Dockerfile
    container_name: ${DOCKER_ALERT_SERVICE_CONTAINER_NAME}
    restart: on-failure:1

    depends_on:
      alert-db:
        condition: service_healthy
      kafka:
        condition: service_healthy    

    environment:
      ALERT_SERVICE_PORT: ${DOCKER_ALERT_SERVICE_PORT}
      ALERT_SERVICE_GRPC_SERVER_PORT: ${DOCKER_ALERT_SERVICE_GRPC_PORT}

      ALERT_SERVICE_DB_URL: ${DOCKER_POSTGRES_ALERT_DB_URL}
      ALERT_SERVICE_DB_USERNAME: ${DOCKER_POSTGRES_USER}
      ALERT_SERVICE_DB_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}

      ALERT_SERVICE_REDIS_HOST: ${DOCKER_ALERT_REDIS_CONTAINER_NAME}
      ALERT_SERVICE_REDIS_PORT: ${DOCKER_ALERT_SERVICE_REDIS_PORT}

      KAFKA_BOOTSTRAP_SERVERS: ${DOCKER_KAFKA_SERVER}

      DEVICE_SERVICE_ADDRESS: ${DOCKER_DEVICE_SERVICE_CONTAINER_NAME}
      DEVICE_SERVICE_GRPC_SERVER_PORT: ${DOCKER_DEVICE_SERVICE_GRPC_PORT}

    networks:
      - ezhomenet

  app:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    restart: on-failure:1

    environment:
      API_GATEWAY_SERVICE_PORT: ${DOCKER_API_GATEWAY_PORT}
      API_GATEWAY_AUTH_URL: ${DOCKER_API_GATEWAY_AUTH_URL}
      JWT.SECRET: ${JWT_SECRET}

      AUTH_SERVICE_CONTAINER_NAME: ${DOCKER_AUTH_SERVICE_CONTAINER_NAME}
      AUTH_SERVICE_PORT: ${DOCKER_AUTH_SERVICE_PORT}

      USER_SERVICE_CONTAINER_NAME: ${DOCKER_USER_SERVICE_CONTAINER_NAME}
      USER_SERVICE_PORT: ${DOCKER_USER_SERVICE_PORT}

      DEVICE_REGISTRY_SERVICE_CONTAINER_NAME: ${DOCKER_DEVICE_REGISTRY_SERVICE_CONTAINER_NAME}
      DEVICE_REGISTRY_SERVICE_PORT: ${DOCKER_DEVICE_REGISTRY_SERVICE_PORT}

      DEVICE_SERVICE_CONTAINER_NAME: ${DOCKER_DEVICE_SERVICE_CONTAINER_NAME}
      DEVICE_SERVICE_PORT: ${DOCKER_DEVICE_SERVICE_PORT}

      INGESTION_SERVICE_CONTAINER_NAME: ${DOCKER_INGESTION_SERVICE_CONTAINER_NAME}
      INGESTION_SERVICE_PORT: ${DOCKER_INGESTION_SERVICE_PORT}

      ALERT_SERVICE_CONTAINER_NAME: ${DOCKER_ALERT_SERVICE_CONTAINER_NAME}
      ALERT_SERVICE_PORT: ${DOCKER_ALERT_SERVICE_PORT}

    ports:
      - "4000:4000"
      
    networks:
      - ezhomenet

networks:
  ezhomenet:

volumes:
  user_data:
  auth_data:
  device_registry_data:
  device_data:
  ingestion_redis_data:
  usage_data:
  alert_data:
  alert_redis_data:

