spring.config.import=optional:file:.env[.properties]

spring.application.name=alert-service

server.port=${ALERT_SERVICE_PORT}

# postgres properties
spring.datasource.url=${ALERT_SERVICE_DB_URL}
spring.datasource.username=${ALERT_SERVICE_DB_USERNAME}
spring.datasource.password=${ALERT_SERVICE_DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
