spring.config.import=optional:file:.env[.properties]

spring.application.name=ingestion-service
server.port=${INGESTION_SERVICE_PORT}
grpc.server.port=${INGESTION_SERVICE_GRPC_SERVER_PORT}

spring.data.redis.host=${INGESTION_SERVICE_REDIS_HOST}
spring.data.redis.port=${INGESTION_SERVICE_REDIS_PORT}

device.service.address=${DEVICE_SERVICE_ADDRESS}
device.service.grpc.port=${DEVICE_SERVICE_GRPC_SERVER_PORT}
