spring.config.import=optional:file:.env[.properties]

spring.application.name=device-service
server.port=${DEVICE_SERVICE_PORT}
grpc.server.port=${DEVICE_SERVICE_GRPC_SERVER_PORT}

device.registry.service.address=${DEVICE_REGISTRY_SERVICE_ADDRESS}
device.registry.service.grpc.port=${DEVICE_REGISTRY_SERVICE_GRPC_SERVER_PORT}

ingestion.service.address=${INGESTION_SERVICE_ADDRESS}
ingestion.service.grpc.port=${INGESTION_SERVICE_GRPC_SERVER_PORT}

# postgres properties
spring.datasource.url=${DEVICE_SERVICE_DB_URL}
spring.datasource.username=${DEVICE_SERVICE_DB_USERNAME}
spring.datasource.password=${DEVICE_SERVICE_DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
